# Generated by Django 5.0.2 on 2024-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('about', models.TextField(blank=True, max_length=600, verbose_name='Комментарий')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
            ],
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='emails',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Список адресов'),
        ),
    ]
