# Generated by Django 5.0.2 on 2024-03-03 19:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_letter_owner_alter_mailing_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.AddField(
            model_name='mailing',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец рассылок'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало рассылок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('ended', 'Закончена')], default='created', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='log',
            name='last_try_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 19, 42, 46, 524730, tzinfo=datetime.timezone.utc), verbose_name='Время последней рассылки'),
        ),
    ]
