# Generated by Django 5.0.2 on 2024-03-03 21:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_log_last_try_dt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='log',
            name='last_try_dt',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 21, 13, 34, 103430, tzinfo=datetime.timezone.utc), verbose_name='Время последней рассылки'),
        ),
    ]
