# Generated by Django 5.0.2 on 2024-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Обложка')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Когда создан')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_published', models.BooleanField(verbose_name='Опубликовано')),
            ],
        ),
    ]
